export const user =[
    {
        id: 1,
        name: {
            firstname: "Lovelyn",
            lastname: "Magsino",
        },
        course: "BS INFORMATION TECHNOLOGY",
        year: 3,
        section: "A",
        userType: "Student",
        username: "@Amazinglove",
        password: "lovelyn187",
    },
    {
        id: 2,
        name: {
            firstname: "Steven",
            lastname: "chui",
        },
        course: "BS COMPUTER SCIENCE",
        year: 4,
        section: "A",
        userType: "Student",
        username: "ChuiSTEVEN",
        password: "_chuii123",
    },
    {
        id: 3,
        name: {
            firstname: "Anderson",
            lastname: "Pilipino",
        },
        course: "BS COMPUTER ENGINEERING",
        year: 3,
        section: "B",
        userType: "Student",
        username: "_143Anderson",
        password: "philippines",
    },
    {
        id: 4,
        name: {
            firstname: "Jerry",
            lastname: "Magales",
        },
        course: "BS ACCOUNTANCY",
        year: '2',
        section: "C",
        userType: "Student",
        username: "_23JerryMagales",
        password: "@magales",
    },
    {
        id: 5,
        name: {
            firstname: "Melrose",
            lastname: "Valiente",
        },
        course: "BS CRIMINOLOGY",
        year: 3,
        section: "A",
        userType: "Student",
        username: "MELROSE3657",
        password: "milkyway",
    },
    {
        id: 6,
        name: {
            firstname: "Jerry",
            lastname: "Ale",
        },
        course: "BS INFORMATION TECHNOLOGY",
        year: '',
        section: "",
        userType: "Teacher",
        username: "@ALEJERRY",
        password: "ALE_JERRY",
    },
    {
        id: 7,
        name: {
            firstname: "Nikka",
            lastname: "Agon",
        },
        course: "BS CRIMINOLOGY",
        year: '3',
        section: "B",
        userType: "Student",
        username: "_nikka975",
        password: "1nik2ka3",
    },
    {
        id: 8,
        name: {
            firstname: "Narcydel",
            lastname: "Sagubay",
        },
        course: "BSIT- FBSM",
        year: 3,
        section: "B",
        userType: "Student",
        username: "Narcy_bay",
        password: "kickoff",
    },
    {
        id: 9,
        name: {
            firstname: "Mylene",
            lastname: "Magsino",
        },
        course: "BS CIVIL ENGINEERING",
        year: 3,
        section: "A",
        userType: "Student",
        username: "MayMYlene_7",
        password: "jezzengineer",
    },
    {
        id: 10,
        name: {
            firstname: "Daisy Jane",
            lastname: "Toring",
        },
        course: "BS Information Technology",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "maam_daisy",
        password: "daisyjane",
    },
    {
        id: 11,
        name: {
            firstname: "Jannika",
            lastname: "Perez",
        },
        course: "BS COMPUTER SCIENCE",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "maam_NIKKA",
        password: "JANIKKA",
    },
    {
        id: 12,
        name: {
            firstname: "Jovy",
            lastname: "Baldapan",
        },
        course: "BS ACCOUNTANCY",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "@Baldapan_Jovy",
        password: "jovy_b",
    },
    {
        id: 13,
        name: {
            firstname: "Ashley",
            lastname: "Ortega",
        },
        course: "BS CRIMINOLOGY",
        year: '4',
        section: "C ",
        userType: "Student",
        username: "ortega_ashley",
        password: "ash4376",
    },
    {
        id: 14,
        name: {
            firstname: "Jocelyn",
            lastname: "Jala",
        },
        course: "BS ELECTRONIC TECHNOLOGY",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "mjala_jocelyn",
        password: "dmaam@JALA",
    },
    {
        id: 15,
        name: {
            firstname: "Natasha",
            lastname: "Toring",
        },
        course: "BS OFFICE ADMINISTRATION",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "maam_tasha",
        password: "dTNatasha348975",
    },
    {
        id: 16,
        name: {
            firstname: "asha",
            lastname: "oring",
        },
        course: "BS OFFICE ADMINISTRATION",
        year: '1',
        section: "D",
        userType: "Student",
        username: "asha",
        password: "O_asha3485",
    },
    {
        id: 17,
        name: {
            firstname: "crisia",
            lastname: "0ng",
        },
        course: "BS INDUSTRIAL TECHNOLOGY",
        year: '2',
        section: "C",
        userType: "Student",
        username: "akasiang",
        password: "S348975",
    },
    {
        id: 18,
        name: {
            firstname: "Victoria",
            lastname: "Toring",
        },
        course: "BS PSYCHOLOGY",
        year: '',
        section: " ",
        userType: "Teacher",
        username: "maam_VIC",
        password: "dTORING5",
    },
    {
        id: 19,
        name: {
            firstname: "LUISA",
            lastname: "ORIGENES",
        },
        course: "BS PSYCHOLOGY",
        year: '4',
        section: "B ",
        userType: "Student",
        username: "luisa_origenes",
        password: "348975",
    },
    {
        id: 20,
        name: {
            firstname: "nikka jean",
            lastname: "torreon",
        },
        course: "BS TOURISM MANAGEMENT",
        year: '2',
        section: "A",
        userType: "Student",
        username: "@atshi_jean",
        password: "dTAYLORS635",
    },
];